apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-dns
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: dns-update
              image: ghcr.io/csepulveda/dns-update-job:1.0.1
              env:
                - name: CLOUDFLARE_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: cloudflare-dns-secret
                      key: CLOUDFLARE_API_KEY
                - name: CLOUDFLARE_EMAIL
                  valueFrom:
                    secretKeyRef:
                      name: cloudflare-dns-secret
                      key: CLOUDFLARE_EMAIL
                - name: DOMAIN
                  valueFrom:
                    secretKeyRef:
                      name: cloudflare-dns-secret
                      key: DOMAIN
                - name: RECORD
                  valueFrom:
                    secretKeyRef:
                      name: cloudflare-dns-secret
                      key: RECORD
          restartPolicy: OnFailure